### ISSUE TITLE
No example of creating user using SAMR protocol

### ISSUE THREAD

**Issue by gredwhite** [AgNO3/jcifs-ng#337]
I have local Samba server. I start it using docker-compose file.

```
services:
  samba:
    image: instantlinux/samba-dc:latest
    container_name: samba-dc
    cap_add:
      - CAP_SYS_ADMIN
    hostname: my.company
    environment:
      DOMAIN_ACTION: provision
      REALM: my.company
    volumes:
      - etc:/etc/samba
      - lib:/var/lib/samba
    ports:
      - "53:53"
      - "53:53/udp"
      - "88:88"
      - "88:88/udp"
      - "389:389"
      - "139:139"
      - "446:445"
    secrets:
      - samba-admin-password
```

I want to implement a java program to create a new user in Sambe. 
SAMR protocol is suitable for this
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-samr/d0360910-33dd-4e3c-b5a2-26daf95f5ffa

In that library (jcifs-ng) there are some classes/files which contain `samr` as a part of the name. All of them are located in that package: https://github.com/AgNO3/jcifs-ng/tree/master/src/main/java/jcifs/dcerpc/msrpc

But I can't find any example of usage such classes.

Also I asked chatGpt to help me and it returned me the following code:
```
import jcifs.smb.*;

public class SambaUserCreationExample {
    public static void main(String[] args) {
        String username = "admin";
        String password = "admin_password";
        String domainController = "smb://domain_controller_ip_address";
        String userToCreate = "new_user";
        String userPassword = "new_user_password";
        String groupName = "users";

        try {
            NtlmPasswordAuthentication auth = new NtlmPasswordAuthentication("", username, password);
            String remotePath = domainController + "/samr";

            SmbFile smbFile = new SmbFile(remotePath, auth);
            SamrDomain domain = new SamrDomain(smbFile, auth);

            // Create the new user
            SamrUser newUser = domain.createUser(userToCreate, SamrUser.USER_NORMAL_ACCOUNT);
            newUser.setPassword(userPassword);
            newUser.commit();

            // Add the new user to a group
            SamrGroup group = domain.getGroup(groupName);
            group.addUser(newUser);
            group.commit();
            
            System.out.println("New user created successfully!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

But I can't find SamrUser, SamrDomain  classes in any jcif library 

Could you please provide working example of program creating the user ?
